### ISSUE TITLE
Flowchart Diagram 

### ISSUE THREAD

**Issue by ptoulino** [Project-PICK/Project-PICK#25]
Create a flowchart digram and gain approval from the lead programmer/team members.

**Comment by ptoulino** [comment]
![FlowDiagram (1) (4)](https://user-images.githubusercontent.com/68033681/95640770-415b5500-0a53-11eb-8267-1d6efa11c3bd.png)


@itravers, please review any final changes that need to be addressed

**Comment by itravers** [comment]
This looks mostly good and I think I'll be able to work off of it.
Please Add the following:

1.  A Name for each window. The name should be short, perhaps two words, First word capital & camel case. I'll be using the names on the chart at the variable names. So think in that direction when naming them.
2. Put a title up top.
3. Put the project name somewhere.
4. Make sure to attribute yourself as the creator/author of the chart, because it's awesome and you deserve the recognition.
